// Code generated by mockery v1.0.0
package v1

import api "github.com/slok/ragnarok/api"

import mock "github.com/stretchr/testify/mock"
import v1 "github.com/slok/ragnarok/api/chaos/v1"
import watch "github.com/slok/ragnarok/apimachinery/watch"

// ExperimentClientInterface is an autogenerated mock type for the ExperimentClientInterface type
type ExperimentClientInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: experiment
func (_m *ExperimentClientInterface) Create(experiment *v1.Experiment) (*v1.Experiment, error) {
	ret := _m.Called(experiment)

	var r0 *v1.Experiment
	if rf, ok := ret.Get(0).(func(*v1.Experiment) *v1.Experiment); ok {
		r0 = rf(experiment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Experiment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.Experiment) error); ok {
		r1 = rf(experiment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *ExperimentClientInterface) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *ExperimentClientInterface) Get(id string) (*v1.Experiment, error) {
	ret := _m.Called(id)

	var r0 *v1.Experiment
	if rf, ok := ret.Get(0).(func(string) *v1.Experiment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Experiment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: opts
func (_m *ExperimentClientInterface) List(opts api.ListOptions) ([]*v1.Experiment, error) {
	ret := _m.Called(opts)

	var r0 []*v1.Experiment
	if rf, ok := ret.Get(0).(func(api.ListOptions) []*v1.Experiment); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.Experiment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(api.ListOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: experiment
func (_m *ExperimentClientInterface) Update(experiment *v1.Experiment) (*v1.Experiment, error) {
	ret := _m.Called(experiment)

	var r0 *v1.Experiment
	if rf, ok := ret.Get(0).(func(*v1.Experiment) *v1.Experiment); ok {
		r0 = rf(experiment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Experiment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.Experiment) error); ok {
		r1 = rf(experiment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Watch provides a mock function with given fields: opts
func (_m *ExperimentClientInterface) Watch(opts api.ListOptions) (watch.Watcher, error) {
	ret := _m.Called(opts)

	var r0 watch.Watcher
	if rf, ok := ret.Get(0).(func(api.ListOptions) watch.Watcher); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Watcher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(api.ListOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
