// Code generated by mockery v1.0.0
package v1

import api "github.com/slok/ragnarok/api"
import mock "github.com/stretchr/testify/mock"

import watch "github.com/slok/ragnarok/apimachinery/watch"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Create provides a mock function with given fields: obj
func (_m *Client) Create(obj api.Object) (api.Object, error) {
	ret := _m.Called(obj)

	var r0 api.Object
	if rf, ok := ret.Get(0).(func(api.Object) api.Object); ok {
		r0 = rf(obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.Object)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(api.Object) error); ok {
		r1 = rf(obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Client) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *Client) Get(id string) (api.Object, error) {
	ret := _m.Called(id)

	var r0 api.Object
	if rf, ok := ret.Get(0).(func(string) api.Object); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.Object)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: opts
func (_m *Client) List(opts api.ListOptions) (api.ObjectList, error) {
	ret := _m.Called(opts)

	var r0 api.ObjectList
	if rf, ok := ret.Get(0).(func(api.ListOptions) api.ObjectList); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.ObjectList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(api.ListOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: obj
func (_m *Client) Update(obj api.Object) (api.Object, error) {
	ret := _m.Called(obj)

	var r0 api.Object
	if rf, ok := ret.Get(0).(func(api.Object) api.Object); ok {
		r0 = rf(obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.Object)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(api.Object) error); ok {
		r1 = rf(obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Watch provides a mock function with given fields: opts
func (_m *Client) Watch(opts api.ListOptions) (watch.Watcher, error) {
	ret := _m.Called(opts)

	var r0 watch.Watcher
	if rf, ok := ret.Get(0).(func(api.ListOptions) watch.Watcher); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Watcher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(api.ListOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
