// Code generated by protoc-gen-go. DO NOT EDIT.
// source: failure/failure.proto

/*
Package failure is a generated protocol buffer package.

It is generated from these files:
	failure/failure.proto

It has these top-level messages:
	NodeId
	FailureId
	Failure
	FailuresExpectedState
*/
package failure

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// State is the state a failure can be.
type State int32

const (
	State_UNKNOWN   State = 0
	State_ENABLED   State = 1
	State_REVERTING State = 2
	State_DISABLED  State = 3
)

var State_name = map[int32]string{
	0: "UNKNOWN",
	1: "ENABLED",
	2: "REVERTING",
	3: "DISABLED",
}
var State_value = map[string]int32{
	"UNKNOWN":   0,
	"ENABLED":   1,
	"REVERTING": 2,
	"DISABLED":  3,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// NodeId is a node id.
type NodeId struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *NodeId) Reset()                    { *m = NodeId{} }
func (m *NodeId) String() string            { return proto.CompactTextString(m) }
func (*NodeId) ProtoMessage()               {}
func (*NodeId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// FailureId is a failure id.
type FailureId struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *FailureId) Reset()                    { *m = FailureId{} }
func (m *FailureId) String() string            { return proto.CompactTextString(m) }
func (*FailureId) ProtoMessage()               {}
func (*FailureId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FailureId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Failure represents an failure.
type Failure struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Definition string `protobuf:"bytes,3,opt,name=definition" json:"definition,omitempty"`
}

func (m *Failure) Reset()                    { *m = Failure{} }
func (m *Failure) String() string            { return proto.CompactTextString(m) }
func (*Failure) ProtoMessage()               {}
func (*Failure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Failure) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Failure) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Failure) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

// FailuresExpectedState reprensents the state of the failures.
type FailuresExpectedState struct {
	RunningFailureId  []string `protobuf:"bytes,1,rep,name=running_failure_id,json=runningFailureId" json:"running_failure_id,omitempty"`
	RevertedFailureId []string `protobuf:"bytes,2,rep,name=reverted_failure_id,json=revertedFailureId" json:"reverted_failure_id,omitempty"`
}

func (m *FailuresExpectedState) Reset()                    { *m = FailuresExpectedState{} }
func (m *FailuresExpectedState) String() string            { return proto.CompactTextString(m) }
func (*FailuresExpectedState) ProtoMessage()               {}
func (*FailuresExpectedState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FailuresExpectedState) GetRunningFailureId() []string {
	if m != nil {
		return m.RunningFailureId
	}
	return nil
}

func (m *FailuresExpectedState) GetRevertedFailureId() []string {
	if m != nil {
		return m.RevertedFailureId
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeId)(nil), "failure.NodeId")
	proto.RegisterType((*FailureId)(nil), "failure.FailureId")
	proto.RegisterType((*Failure)(nil), "failure.Failure")
	proto.RegisterType((*FailuresExpectedState)(nil), "failure.FailuresExpectedState")
	proto.RegisterEnum("failure.State", State_name, State_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FailureState service

type FailureStateClient interface {
	// FailureStateList asks for a list of the failures that should begin, continue or stop.
	FailureStateList(ctx context.Context, in *NodeId, opts ...grpc.CallOption) (FailureState_FailureStateListClient, error)
	// GetFailure asks for a failure.
	GetFailure(ctx context.Context, in *FailureId, opts ...grpc.CallOption) (*Failure, error)
}

type failureStateClient struct {
	cc *grpc.ClientConn
}

func NewFailureStateClient(cc *grpc.ClientConn) FailureStateClient {
	return &failureStateClient{cc}
}

func (c *failureStateClient) FailureStateList(ctx context.Context, in *NodeId, opts ...grpc.CallOption) (FailureState_FailureStateListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FailureState_serviceDesc.Streams[0], c.cc, "/failure.FailureState/FailureStateList", opts...)
	if err != nil {
		return nil, err
	}
	x := &failureStateFailureStateListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FailureState_FailureStateListClient interface {
	Recv() (*FailuresExpectedState, error)
	grpc.ClientStream
}

type failureStateFailureStateListClient struct {
	grpc.ClientStream
}

func (x *failureStateFailureStateListClient) Recv() (*FailuresExpectedState, error) {
	m := new(FailuresExpectedState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *failureStateClient) GetFailure(ctx context.Context, in *FailureId, opts ...grpc.CallOption) (*Failure, error) {
	out := new(Failure)
	err := grpc.Invoke(ctx, "/failure.FailureState/GetFailure", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FailureState service

type FailureStateServer interface {
	// FailureStateList asks for a list of the failures that should begin, continue or stop.
	FailureStateList(*NodeId, FailureState_FailureStateListServer) error
	// GetFailure asks for a failure.
	GetFailure(context.Context, *FailureId) (*Failure, error)
}

func RegisterFailureStateServer(s *grpc.Server, srv FailureStateServer) {
	s.RegisterService(&_FailureState_serviceDesc, srv)
}

func _FailureState_FailureStateList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NodeId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FailureStateServer).FailureStateList(m, &failureStateFailureStateListServer{stream})
}

type FailureState_FailureStateListServer interface {
	Send(*FailuresExpectedState) error
	grpc.ServerStream
}

type failureStateFailureStateListServer struct {
	grpc.ServerStream
}

func (x *failureStateFailureStateListServer) Send(m *FailuresExpectedState) error {
	return x.ServerStream.SendMsg(m)
}

func _FailureState_GetFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailureId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FailureStateServer).GetFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/failure.FailureState/GetFailure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FailureStateServer).GetFailure(ctx, req.(*FailureId))
	}
	return interceptor(ctx, in, info, handler)
}

var _FailureState_serviceDesc = grpc.ServiceDesc{
	ServiceName: "failure.FailureState",
	HandlerType: (*FailureStateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFailure",
			Handler:    _FailureState_GetFailure_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FailureStateList",
			Handler:       _FailureState_FailureStateList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "failure/failure.proto",
}

func init() { proto.RegisterFile("failure/failure.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0xdf, 0xb6, 0xaf, 0xab, 0x3d, 0x4e, 0x8d, 0x47, 0x06, 0x65, 0xc2, 0x90, 0x5e, 0x0d,
	0x91, 0x2a, 0xf3, 0x5e, 0x50, 0x16, 0x47, 0x71, 0x46, 0xe8, 0xfc, 0x73, 0x39, 0xaa, 0xc9, 0x24,
	0xa0, 0xe9, 0xe8, 0x52, 0xf1, 0x2b, 0xf8, 0xad, 0xc5, 0x34, 0x9d, 0xa5, 0xec, 0x2a, 0x39, 0xcf,
	0xef, 0xe1, 0x9c, 0x93, 0x27, 0xd0, 0x5b, 0x64, 0xf2, 0xbd, 0x2c, 0xc4, 0x99, 0x3d, 0xe3, 0x65,
	0x91, 0xeb, 0x1c, 0x7d, 0x5b, 0x46, 0x21, 0x74, 0x58, 0xce, 0x45, 0xc2, 0x71, 0x0f, 0x5c, 0xc9,
	0x43, 0xe7, 0xd8, 0x19, 0x06, 0xa9, 0x2b, 0x79, 0x74, 0x04, 0xc1, 0x4d, 0x65, 0xda, 0x00, 0xef,
	0xc0, 0xb7, 0xb0, 0x8d, 0x10, 0xe1, 0xbf, 0xca, 0x3e, 0x44, 0xe8, 0x1a, 0xc5, 0xdc, 0x71, 0x00,
	0xc0, 0xc5, 0x42, 0x2a, 0xa9, 0x65, 0xae, 0x42, 0xcf, 0x90, 0x86, 0x12, 0x95, 0xd0, 0xb3, 0xed,
	0x56, 0xf4, 0x6b, 0x29, 0x5e, 0xb5, 0xe0, 0x33, 0x9d, 0x69, 0x81, 0xa7, 0x80, 0x45, 0xa9, 0x94,
	0x54, 0x6f, 0x73, 0xbb, 0xf1, 0xdc, 0x0c, 0xf3, 0x86, 0x41, 0x4a, 0x2c, 0xf9, 0xdb, 0x32, 0x86,
	0xc3, 0x42, 0x7c, 0x8a, 0x42, 0x0b, 0xde, 0xb4, 0xbb, 0xc6, 0x7e, 0x50, 0xa3, 0xb5, 0xff, 0xe4,
	0x12, 0xb6, 0xaa, 0x31, 0x3b, 0xe0, 0x3f, 0xb2, 0x5b, 0x76, 0xff, 0xcc, 0xc8, 0xbf, 0xdf, 0x82,
	0xb2, 0xab, 0xeb, 0x29, 0x1d, 0x13, 0x07, 0x77, 0x21, 0x48, 0xe9, 0x13, 0x4d, 0x1f, 0x12, 0x36,
	0x21, 0x2e, 0x76, 0x61, 0x7b, 0x9c, 0xcc, 0x2a, 0xe8, 0x8d, 0xbe, 0x1d, 0xe8, 0xda, 0x6e, 0x55,
	0x1f, 0x0a, 0xa4, 0x59, 0x4f, 0xe5, 0x4a, 0xe3, 0x7e, 0x5c, 0x47, 0x5f, 0x05, 0xdd, 0x1f, 0xac,
	0x85, 0x8d, 0x6f, 0x3e, 0x77, 0x70, 0x04, 0x30, 0x11, 0xba, 0x0e, 0x18, 0xdb, 0xfe, 0x84, 0xf7,
	0x49, 0x5b, 0x7b, 0xe9, 0x98, 0x8f, 0xbd, 0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0x60, 0x12, 0xb8,
	0xe3, 0xf1, 0x01, 0x00, 0x00,
}
