// Code generated by protoc-gen-go. DO NOT EDIT.
// source: failure/failure.proto

/*
Package failure is a generated protocol buffer package.

It is generated from these files:
	failure/failure.proto

It has these top-level messages:
	NodeId
	FailureId
	Failure
	FailuresExpectedState
*/
package failure

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// State is the state a failure can be.
type State int32

const (
	State_UNKNOWN   State = 0
	State_ENABLED   State = 1
	State_REVERTING State = 2
	State_DISABLED  State = 3
)

var State_name = map[int32]string{
	0: "UNKNOWN",
	1: "ENABLED",
	2: "REVERTING",
	3: "DISABLED",
}
var State_value = map[string]int32{
	"UNKNOWN":   0,
	"ENABLED":   1,
	"REVERTING": 2,
	"DISABLED":  3,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// NodeId is a node id.
type NodeId struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *NodeId) Reset()                    { *m = NodeId{} }
func (m *NodeId) String() string            { return proto.CompactTextString(m) }
func (*NodeId) ProtoMessage()               {}
func (*NodeId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// FailureId is a failure id.
type FailureId struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *FailureId) Reset()                    { *m = FailureId{} }
func (m *FailureId) String() string            { return proto.CompactTextString(m) }
func (*FailureId) ProtoMessage()               {}
func (*FailureId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FailureId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Failure represents an failure.
type Failure struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Definition string `protobuf:"bytes,3,opt,name=definition" json:"definition,omitempty"`
}

func (m *Failure) Reset()                    { *m = Failure{} }
func (m *Failure) String() string            { return proto.CompactTextString(m) }
func (*Failure) ProtoMessage()               {}
func (*Failure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Failure) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Failure) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Failure) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

// FailuresExpectedState reprensents the state of the failures.
type FailuresExpectedState struct {
	RunningFailureId  []string `protobuf:"bytes,1,rep,name=running_failure_id,json=runningFailureId" json:"running_failure_id,omitempty"`
	RevertedFailureId []string `protobuf:"bytes,2,rep,name=reverted_failure_id,json=revertedFailureId" json:"reverted_failure_id,omitempty"`
}

func (m *FailuresExpectedState) Reset()                    { *m = FailuresExpectedState{} }
func (m *FailuresExpectedState) String() string            { return proto.CompactTextString(m) }
func (*FailuresExpectedState) ProtoMessage()               {}
func (*FailuresExpectedState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FailuresExpectedState) GetRunningFailureId() []string {
	if m != nil {
		return m.RunningFailureId
	}
	return nil
}

func (m *FailuresExpectedState) GetRevertedFailureId() []string {
	if m != nil {
		return m.RevertedFailureId
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeId)(nil), "failure.NodeId")
	proto.RegisterType((*FailureId)(nil), "failure.FailureId")
	proto.RegisterType((*Failure)(nil), "failure.Failure")
	proto.RegisterType((*FailuresExpectedState)(nil), "failure.FailuresExpectedState")
	proto.RegisterEnum("failure.State", State_name, State_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FailureStatus service

type FailureStatusClient interface {
	// FailureStateList asks for a list of the failures that should begin, continue or stop.
	FailureStateList(ctx context.Context, in *NodeId, opts ...grpc.CallOption) (FailureStatus_FailureStateListClient, error)
	// GetFailure asks for a failure.
	GetFailure(ctx context.Context, in *FailureId, opts ...grpc.CallOption) (*Failure, error)
}

type failureStatusClient struct {
	cc *grpc.ClientConn
}

func NewFailureStatusClient(cc *grpc.ClientConn) FailureStatusClient {
	return &failureStatusClient{cc}
}

func (c *failureStatusClient) FailureStateList(ctx context.Context, in *NodeId, opts ...grpc.CallOption) (FailureStatus_FailureStateListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FailureStatus_serviceDesc.Streams[0], c.cc, "/failure.FailureStatus/FailureStateList", opts...)
	if err != nil {
		return nil, err
	}
	x := &failureStatusFailureStateListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FailureStatus_FailureStateListClient interface {
	Recv() (*FailuresExpectedState, error)
	grpc.ClientStream
}

type failureStatusFailureStateListClient struct {
	grpc.ClientStream
}

func (x *failureStatusFailureStateListClient) Recv() (*FailuresExpectedState, error) {
	m := new(FailuresExpectedState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *failureStatusClient) GetFailure(ctx context.Context, in *FailureId, opts ...grpc.CallOption) (*Failure, error) {
	out := new(Failure)
	err := grpc.Invoke(ctx, "/failure.FailureStatus/GetFailure", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FailureStatus service

type FailureStatusServer interface {
	// FailureStateList asks for a list of the failures that should begin, continue or stop.
	FailureStateList(*NodeId, FailureStatus_FailureStateListServer) error
	// GetFailure asks for a failure.
	GetFailure(context.Context, *FailureId) (*Failure, error)
}

func RegisterFailureStatusServer(s *grpc.Server, srv FailureStatusServer) {
	s.RegisterService(&_FailureStatus_serviceDesc, srv)
}

func _FailureStatus_FailureStateList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NodeId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FailureStatusServer).FailureStateList(m, &failureStatusFailureStateListServer{stream})
}

type FailureStatus_FailureStateListServer interface {
	Send(*FailuresExpectedState) error
	grpc.ServerStream
}

type failureStatusFailureStateListServer struct {
	grpc.ServerStream
}

func (x *failureStatusFailureStateListServer) Send(m *FailuresExpectedState) error {
	return x.ServerStream.SendMsg(m)
}

func _FailureStatus_GetFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailureId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FailureStatusServer).GetFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/failure.FailureStatus/GetFailure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FailureStatusServer).GetFailure(ctx, req.(*FailureId))
	}
	return interceptor(ctx, in, info, handler)
}

var _FailureStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "failure.FailureStatus",
	HandlerType: (*FailureStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFailure",
			Handler:    _FailureStatus_GetFailure_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FailureStateList",
			Handler:       _FailureStatus_FailureStateList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "failure/failure.proto",
}

func init() { proto.RegisterFile("failure/failure.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x6f, 0x4b, 0xc3, 0x30,
	0x10, 0xc6, 0x6d, 0xa7, 0x9b, 0x3d, 0x9d, 0xc6, 0x93, 0x41, 0x99, 0x30, 0x64, 0xaf, 0x86, 0xc8,
	0x94, 0xf9, 0x5e, 0x50, 0x16, 0x47, 0x71, 0x46, 0xe8, 0xfc, 0xf3, 0x72, 0x4c, 0x73, 0x93, 0x80,
	0xa6, 0xa3, 0x4b, 0xc5, 0xcf, 0xe0, 0xa7, 0x96, 0xa5, 0xe9, 0x2c, 0x65, 0xaf, 0x92, 0x7b, 0x7e,
	0x0f, 0x77, 0x97, 0x27, 0xd0, 0x9a, 0xcf, 0xd4, 0x67, 0x96, 0xd2, 0x85, 0x3b, 0xfb, 0x8b, 0x34,
	0x31, 0x09, 0x36, 0x5c, 0xd9, 0x0d, 0xa1, 0x2e, 0x12, 0x49, 0x91, 0xc4, 0x03, 0xf0, 0x95, 0x0c,
	0xbd, 0x53, 0xaf, 0x17, 0xc4, 0xbe, 0x92, 0xdd, 0x13, 0x08, 0xee, 0x72, 0xd3, 0x06, 0xf8, 0x00,
	0x0d, 0x07, 0xab, 0x08, 0x11, 0xb6, 0xf5, 0xec, 0x8b, 0x42, 0xdf, 0x2a, 0xf6, 0x8e, 0x1d, 0x00,
	0x49, 0x73, 0xa5, 0x95, 0x51, 0x89, 0x0e, 0x6b, 0x96, 0x94, 0x94, 0x6e, 0x06, 0x2d, 0xd7, 0x6e,
	0xc9, 0x7f, 0x16, 0xf4, 0x6e, 0x48, 0x4e, 0xcc, 0xcc, 0x10, 0x9e, 0x03, 0xa6, 0x99, 0xd6, 0x4a,
	0x7f, 0x4c, 0xdd, 0xc6, 0x53, 0x3b, 0xac, 0xd6, 0x0b, 0x62, 0xe6, 0xc8, 0xff, 0x96, 0x7d, 0x38,
	0x4e, 0xe9, 0x9b, 0x52, 0x43, 0xb2, 0x6c, 0xf7, 0xad, 0xfd, 0xa8, 0x40, 0x6b, 0xff, 0xd9, 0x35,
	0xec, 0xe4, 0x63, 0xf6, 0xa0, 0xf1, 0x2c, 0xee, 0xc5, 0xe3, 0xab, 0x60, 0x5b, 0xab, 0x82, 0x8b,
	0x9b, 0xdb, 0x31, 0x1f, 0x32, 0x0f, 0x9b, 0x10, 0xc4, 0xfc, 0x85, 0xc7, 0x4f, 0x91, 0x18, 0x31,
	0x1f, 0xf7, 0x61, 0x77, 0x18, 0x4d, 0x72, 0x58, 0x1b, 0xfc, 0x7a, 0xd0, 0x74, 0xdd, 0x56, 0x7d,
	0xb2, 0x25, 0x72, 0x60, 0x25, 0x81, 0xc6, 0x6a, 0x69, 0xf0, 0xb0, 0x5f, 0x64, 0x9f, 0x27, 0xdd,
	0xee, 0xac, 0x85, 0x8d, 0x8f, 0xbe, 0xf4, 0x70, 0x00, 0x30, 0x22, 0x53, 0x24, 0x8c, 0x55, 0x7f,
	0x24, 0xdb, 0xac, 0xaa, 0xbd, 0xd5, 0xed, 0xcf, 0x5e, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd4,
	0x05, 0xac, 0x33, 0xf2, 0x01, 0x00, 0x00,
}
