// Code generated by mockery v1.0.0
package failurestatus

import context "golang.org/x/net/context"
import github_com_slok_ragnarok_grpc_failurestatus "github.com/slok/ragnarok/grpc/failurestatus"
import metadata "google.golang.org/grpc/metadata"
import mock "github.com/stretchr/testify/mock"

// FailureStatus_FailureStateListClient is an autogenerated mock type for the FailureStatus_FailureStateListClient type
type FailureStatus_FailureStateListClient struct {
	mock.Mock
}

// CloseSend provides a mock function with given fields:
func (_m *FailureStatus_FailureStateListClient) CloseSend() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Context provides a mock function with given fields:
func (_m *FailureStatus_FailureStateListClient) Context() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// Header provides a mock function with given fields:
func (_m *FailureStatus_FailureStateListClient) Header() (metadata.MD, error) {
	ret := _m.Called()

	var r0 metadata.MD
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Recv provides a mock function with given fields:
func (_m *FailureStatus_FailureStateListClient) Recv() (*github_com_slok_ragnarok_grpc_failurestatus.FailuresState, error) {
	ret := _m.Called()

	var r0 *github_com_slok_ragnarok_grpc_failurestatus.FailuresState
	if rf, ok := ret.Get(0).(func() *github_com_slok_ragnarok_grpc_failurestatus.FailuresState); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github_com_slok_ragnarok_grpc_failurestatus.FailuresState)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecvMsg provides a mock function with given fields: m
func (_m *FailureStatus_FailureStateListClient) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendMsg provides a mock function with given fields: m
func (_m *FailureStatus_FailureStateListClient) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Trailer provides a mock function with given fields:
func (_m *FailureStatus_FailureStateListClient) Trailer() metadata.MD {
	ret := _m.Called()

	var r0 metadata.MD
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	return r0
}
