// Code generated by mockery v1.0.0
package failurestatus

import context "golang.org/x/net/context"
import github_com_slok_ragnarok_grpc_failurestatus "github.com/slok/ragnarok/grpc/failurestatus"
import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"
import pb "github.com/slok/ragnarok/api/chaos/v1/pb"

// FailureStatusClient is an autogenerated mock type for the FailureStatusClient type
type FailureStatusClient struct {
	mock.Mock
}

// FailureStateList provides a mock function with given fields: ctx, in, opts
func (_m *FailureStatusClient) FailureStateList(ctx context.Context, in *github_com_slok_ragnarok_grpc_failurestatus.NodeId, opts ...grpc.CallOption) (github_com_slok_ragnarok_grpc_failurestatus.FailureStatus_FailureStateListClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 github_com_slok_ragnarok_grpc_failurestatus.FailureStatus_FailureStateListClient
	if rf, ok := ret.Get(0).(func(context.Context, *github_com_slok_ragnarok_grpc_failurestatus.NodeId, ...grpc.CallOption) github_com_slok_ragnarok_grpc_failurestatus.FailureStatus_FailureStateListClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(github_com_slok_ragnarok_grpc_failurestatus.FailureStatus_FailureStateListClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *github_com_slok_ragnarok_grpc_failurestatus.NodeId, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFailure provides a mock function with given fields: ctx, in, opts
func (_m *FailureStatusClient) GetFailure(ctx context.Context, in *github_com_slok_ragnarok_grpc_failurestatus.FailureId, opts ...grpc.CallOption) (*pb.Failure, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.Failure
	if rf, ok := ret.Get(0).(func(context.Context, *github_com_slok_ragnarok_grpc_failurestatus.FailureId, ...grpc.CallOption) *pb.Failure); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.Failure)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *github_com_slok_ragnarok_grpc_failurestatus.FailureId, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
