// Code generated by protoc-gen-go. DO NOT EDIT.
// source: failurestatus/failurestatus.proto

/*
Package failure is a generated protocol buffer package.

It is generated from these files:
	failurestatus/failurestatus.proto

It has these top-level messages:
	NodeId
	FailureId
	Failure
	FailuresExpectedState
*/
package failure

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// State is the state a failure can be.
type State int32

const (
	State_UNKNOWN           State = 0
	State_ENABLED           State = 1
	State_EXECUTING         State = 2
	State_REVERTING         State = 3
	State_DISABLED          State = 4
	State_ERRORED           State = 5
	State_ERRORED_REVERTING State = 6
)

var State_name = map[int32]string{
	0: "UNKNOWN",
	1: "ENABLED",
	2: "EXECUTING",
	3: "REVERTING",
	4: "DISABLED",
	5: "ERRORED",
	6: "ERRORED_REVERTING",
}
var State_value = map[string]int32{
	"UNKNOWN":           0,
	"ENABLED":           1,
	"EXECUTING":         2,
	"REVERTING":         3,
	"DISABLED":          4,
	"ERRORED":           5,
	"ERRORED_REVERTING": 6,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// NodeId is a node id.
type NodeId struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *NodeId) Reset()                    { *m = NodeId{} }
func (m *NodeId) String() string            { return proto.CompactTextString(m) }
func (*NodeId) ProtoMessage()               {}
func (*NodeId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// FailureId is a failure id.
type FailureId struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *FailureId) Reset()                    { *m = FailureId{} }
func (m *FailureId) String() string            { return proto.CompactTextString(m) }
func (*FailureId) ProtoMessage()               {}
func (*FailureId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FailureId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Failure represents an failure.
type Failure struct {
	Id            string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	NodeID        string `protobuf:"bytes,2,opt,name=nodeID" json:"nodeID,omitempty"`
	Definition    string `protobuf:"bytes,3,opt,name=definition" json:"definition,omitempty"`
	CurrentState  State  `protobuf:"varint,4,opt,name=current_state,json=currentState,enum=failure.State" json:"current_state,omitempty"`
	ExpectedState State  `protobuf:"varint,5,opt,name=expected_state,json=expectedState,enum=failure.State" json:"expected_state,omitempty"`
}

func (m *Failure) Reset()                    { *m = Failure{} }
func (m *Failure) String() string            { return proto.CompactTextString(m) }
func (*Failure) ProtoMessage()               {}
func (*Failure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Failure) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Failure) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *Failure) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

func (m *Failure) GetCurrentState() State {
	if m != nil {
		return m.CurrentState
	}
	return State_UNKNOWN
}

func (m *Failure) GetExpectedState() State {
	if m != nil {
		return m.ExpectedState
	}
	return State_UNKNOWN
}

// FailuresExpectedState reprensents the state of the failures.
type FailuresExpectedState struct {
	EnabledFailureId  []string `protobuf:"bytes,1,rep,name=enabled_failure_id,json=enabledFailureId" json:"enabled_failure_id,omitempty"`
	DisabledFailureId []string `protobuf:"bytes,2,rep,name=disabled_failure_id,json=disabledFailureId" json:"disabled_failure_id,omitempty"`
}

func (m *FailuresExpectedState) Reset()                    { *m = FailuresExpectedState{} }
func (m *FailuresExpectedState) String() string            { return proto.CompactTextString(m) }
func (*FailuresExpectedState) ProtoMessage()               {}
func (*FailuresExpectedState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FailuresExpectedState) GetEnabledFailureId() []string {
	if m != nil {
		return m.EnabledFailureId
	}
	return nil
}

func (m *FailuresExpectedState) GetDisabledFailureId() []string {
	if m != nil {
		return m.DisabledFailureId
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeId)(nil), "failure.NodeId")
	proto.RegisterType((*FailureId)(nil), "failure.FailureId")
	proto.RegisterType((*Failure)(nil), "failure.Failure")
	proto.RegisterType((*FailuresExpectedState)(nil), "failure.FailuresExpectedState")
	proto.RegisterEnum("failure.State", State_name, State_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FailureStatus service

type FailureStatusClient interface {
	// FailureStateList asks for a list of the failures that should begin, continue or stop.
	FailureStateList(ctx context.Context, in *NodeId, opts ...grpc.CallOption) (FailureStatus_FailureStateListClient, error)
	// GetFailure asks for a failure.
	GetFailure(ctx context.Context, in *FailureId, opts ...grpc.CallOption) (*Failure, error)
}

type failureStatusClient struct {
	cc *grpc.ClientConn
}

func NewFailureStatusClient(cc *grpc.ClientConn) FailureStatusClient {
	return &failureStatusClient{cc}
}

func (c *failureStatusClient) FailureStateList(ctx context.Context, in *NodeId, opts ...grpc.CallOption) (FailureStatus_FailureStateListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FailureStatus_serviceDesc.Streams[0], c.cc, "/failure.FailureStatus/FailureStateList", opts...)
	if err != nil {
		return nil, err
	}
	x := &failureStatusFailureStateListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FailureStatus_FailureStateListClient interface {
	Recv() (*FailuresExpectedState, error)
	grpc.ClientStream
}

type failureStatusFailureStateListClient struct {
	grpc.ClientStream
}

func (x *failureStatusFailureStateListClient) Recv() (*FailuresExpectedState, error) {
	m := new(FailuresExpectedState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *failureStatusClient) GetFailure(ctx context.Context, in *FailureId, opts ...grpc.CallOption) (*Failure, error) {
	out := new(Failure)
	err := grpc.Invoke(ctx, "/failure.FailureStatus/GetFailure", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FailureStatus service

type FailureStatusServer interface {
	// FailureStateList asks for a list of the failures that should begin, continue or stop.
	FailureStateList(*NodeId, FailureStatus_FailureStateListServer) error
	// GetFailure asks for a failure.
	GetFailure(context.Context, *FailureId) (*Failure, error)
}

func RegisterFailureStatusServer(s *grpc.Server, srv FailureStatusServer) {
	s.RegisterService(&_FailureStatus_serviceDesc, srv)
}

func _FailureStatus_FailureStateList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NodeId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FailureStatusServer).FailureStateList(m, &failureStatusFailureStateListServer{stream})
}

type FailureStatus_FailureStateListServer interface {
	Send(*FailuresExpectedState) error
	grpc.ServerStream
}

type failureStatusFailureStateListServer struct {
	grpc.ServerStream
}

func (x *failureStatusFailureStateListServer) Send(m *FailuresExpectedState) error {
	return x.ServerStream.SendMsg(m)
}

func _FailureStatus_GetFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailureId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FailureStatusServer).GetFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/failure.FailureStatus/GetFailure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FailureStatusServer).GetFailure(ctx, req.(*FailureId))
	}
	return interceptor(ctx, in, info, handler)
}

var _FailureStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "failure.FailureStatus",
	HandlerType: (*FailureStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFailure",
			Handler:    _FailureStatus_GetFailure_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FailureStateList",
			Handler:       _FailureStatus_FailureStateList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "failurestatus/failurestatus.proto",
}

func init() { proto.RegisterFile("failurestatus/failurestatus.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xef, 0x6a, 0xe2, 0x40,
	0x14, 0xc5, 0x37, 0x51, 0xe3, 0xe6, 0xae, 0xc9, 0xc6, 0x59, 0x5c, 0x82, 0x05, 0xb1, 0x7e, 0x92,
	0x52, 0xd2, 0xa2, 0xf4, 0x01, 0xda, 0x66, 0x2a, 0xa1, 0x12, 0x61, 0xac, 0x6d, 0xbf, 0x05, 0x75,
	0x46, 0x18, 0x90, 0xc4, 0x26, 0x13, 0xe8, 0x33, 0xf4, 0x9d, 0xfa, 0x6e, 0x25, 0x93, 0xf1, 0x4f,
	0xad, 0x1f, 0xcf, 0x39, 0xbf, 0x3b, 0xb9, 0xb9, 0x1c, 0x38, 0x5f, 0xcd, 0xf9, 0x3a, 0x4f, 0x59,
	0x26, 0xe6, 0x22, 0xcf, 0xae, 0xbe, 0x29, 0x6f, 0x93, 0x26, 0x22, 0x41, 0x75, 0x65, 0xf6, 0x5c,
	0x30, 0xc2, 0x84, 0xb2, 0x80, 0x22, 0x1b, 0x74, 0x4e, 0x5d, 0xad, 0xab, 0xf5, 0x4d, 0xa2, 0x73,
	0xda, 0x3b, 0x03, 0xf3, 0xa1, 0x84, 0x4e, 0x84, 0x9f, 0x1a, 0xd4, 0x55, 0x7a, 0x9c, 0xa1, 0xff,
	0x60, 0xc4, 0xc5, 0x93, 0xbe, 0xab, 0x4b, 0x4f, 0x29, 0xd4, 0x01, 0xa0, 0x6c, 0xc5, 0x63, 0x2e,
	0x78, 0x12, 0xbb, 0x15, 0x99, 0x1d, 0x38, 0x68, 0x08, 0xd6, 0x32, 0x4f, 0x53, 0x16, 0x8b, 0xa8,
	0xd8, 0x95, 0xb9, 0xd5, 0xae, 0xd6, 0xb7, 0x07, 0xb6, 0xa7, 0x76, 0xf5, 0xa6, 0x85, 0x4b, 0x1a,
	0x0a, 0x92, 0x0a, 0xdd, 0x80, 0xcd, 0xde, 0x37, 0x6c, 0x29, 0x18, 0x55, 0x53, 0xb5, 0x93, 0x53,
	0xd6, 0x96, 0x92, 0xb2, 0x97, 0x43, 0x4b, 0xad, 0x9f, 0xe1, 0xc3, 0x00, 0x5d, 0x02, 0x62, 0xf1,
	0x7c, 0xb1, 0x66, 0x34, 0x52, 0x0f, 0x44, 0xf2, 0xe7, 0x2a, 0x7d, 0x93, 0x38, 0x2a, 0xd9, 0x9f,
	0xc5, 0x83, 0x7f, 0x94, 0x67, 0x3f, 0x70, 0x5d, 0xe2, 0xcd, 0x6d, 0xb4, 0xe3, 0x2f, 0xde, 0xa0,
	0x56, 0x7e, 0xe6, 0x0f, 0xd4, 0x67, 0xe1, 0x63, 0x38, 0x79, 0x09, 0x9d, 0x5f, 0x85, 0xc0, 0xe1,
	0xed, 0xdd, 0x18, 0xfb, 0x8e, 0x86, 0x2c, 0x30, 0xf1, 0x2b, 0xbe, 0x9f, 0x3d, 0x05, 0xe1, 0xc8,
	0xd1, 0x0b, 0x49, 0xf0, 0x33, 0x26, 0x52, 0x56, 0x50, 0x03, 0x7e, 0xfb, 0xc1, 0xb4, 0x64, 0xab,
	0x72, 0x90, 0x90, 0x09, 0xc1, 0xbe, 0x53, 0x43, 0x2d, 0x68, 0x2a, 0x11, 0xed, 0x27, 0x8c, 0xc1,
	0x87, 0x06, 0x96, 0x5a, 0x60, 0x2a, 0x1b, 0x80, 0x30, 0x38, 0x07, 0x06, 0x1b, 0xf3, 0x4c, 0xa0,
	0xbf, 0xbb, 0x73, 0x95, 0x6d, 0x68, 0x77, 0x76, 0xc6, 0xc9, 0x3b, 0x5d, 0x6b, 0x68, 0x00, 0x30,
	0x62, 0x62, 0x5b, 0x02, 0x74, 0xcc, 0x07, 0xb4, 0xed, 0x1c, 0x7b, 0x0b, 0x43, 0xb6, 0x6f, 0xf8,
	0x15, 0x00, 0x00, 0xff, 0xff, 0x34, 0x8a, 0x44, 0x1e, 0xa2, 0x02, 0x00, 0x00,
}
