package mocks

import attack "github.com/slok/ragnarok/attack"
import mock "github.com/stretchr/testify/mock"

// Creater is an autogenerated mock type for the Creater type
type Creater struct {
	mock.Mock
}

// Create provides a mock function with given fields: opts
func (_m *Creater) Create(opts attack.Opts) (attack.Attacker, error) {
	ret := _m.Called(opts)

	var r0 attack.Attacker
	if rf, ok := ret.Get(0).(func(attack.Opts) attack.Attacker); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(attack.Attacker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(attack.Opts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
