// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import types "github.com/slok/ragnarok/types"

// Status is an autogenerated mock type for the Status type
type Status struct {
	mock.Mock
}

// NodeHeartbeat provides a mock function with given fields: id, status
func (_m *Status) NodeHeartbeat(id string, status types.NodeState) {
	_m.Called(id, status)
}

// RegisterNode provides a mock function with given fields: id, tags
func (_m *Status) RegisterNode(id string, tags map[string]string) error {
	ret := _m.Called(id, tags)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]string) error); ok {
		r0 = rf(id, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
