// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nodestatus/nodestatus.proto

/*
Package nodestatus is a generated protocol buffer package.

It is generated from these files:
	nodestatus/nodestatus.proto

It has these top-level messages:
*/
package nodestatus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import github_com_slok_ragnarok_api_cluster_v1_pb "github.com/slok/ragnarok/api/cluster/v1/pb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NodeStatus service

type NodeStatusClient interface {
	// Register registers a node.
	Register(ctx context.Context, in *github_com_slok_ragnarok_api_cluster_v1_pb.Node, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Heartbeat sends the current status of the node and receives
	// the expected status that should have.
	Heartbeat(ctx context.Context, in *github_com_slok_ragnarok_api_cluster_v1_pb.Node, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type nodeStatusClient struct {
	cc *grpc.ClientConn
}

func NewNodeStatusClient(cc *grpc.ClientConn) NodeStatusClient {
	return &nodeStatusClient{cc}
}

func (c *nodeStatusClient) Register(ctx context.Context, in *github_com_slok_ragnarok_api_cluster_v1_pb.Node, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/nodestatus.NodeStatus/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStatusClient) Heartbeat(ctx context.Context, in *github_com_slok_ragnarok_api_cluster_v1_pb.Node, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/nodestatus.NodeStatus/Heartbeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NodeStatus service

type NodeStatusServer interface {
	// Register registers a node.
	Register(context.Context, *github_com_slok_ragnarok_api_cluster_v1_pb.Node) (*google_protobuf.Empty, error)
	// Heartbeat sends the current status of the node and receives
	// the expected status that should have.
	Heartbeat(context.Context, *github_com_slok_ragnarok_api_cluster_v1_pb.Node) (*google_protobuf.Empty, error)
}

func RegisterNodeStatusServer(s *grpc.Server, srv NodeStatusServer) {
	s.RegisterService(&_NodeStatus_serviceDesc, srv)
}

func _NodeStatus_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(github_com_slok_ragnarok_api_cluster_v1_pb.Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStatusServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodestatus.NodeStatus/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStatusServer).Register(ctx, req.(*github_com_slok_ragnarok_api_cluster_v1_pb.Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStatus_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(github_com_slok_ragnarok_api_cluster_v1_pb.Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStatusServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodestatus.NodeStatus/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStatusServer).Heartbeat(ctx, req.(*github_com_slok_ragnarok_api_cluster_v1_pb.Node))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nodestatus.NodeStatus",
	HandlerType: (*NodeStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _NodeStatus_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _NodeStatus_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodestatus/nodestatus.proto",
}

func init() { proto.RegisterFile("nodestatus/nodestatus.proto", fileDescriptorNodestatus) }

var fileDescriptorNodestatus = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0xcb, 0x4f, 0x49,
	0x2d, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0xd6, 0x47, 0x30, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0xb8, 0x10, 0x22, 0x52, 0xd2, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x99, 0xa4, 0xd2,
	0x34, 0xfd, 0xd4, 0xdc, 0x82, 0x92, 0x4a, 0x88, 0x42, 0x29, 0xd3, 0xf4, 0xcc, 0x92, 0x8c, 0xd2,
	0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xe2, 0x9c, 0xfc, 0x6c, 0xfd, 0xa2, 0xc4, 0xf4, 0xbc, 0xc4,
	0xa2, 0xfc, 0x6c, 0xfd, 0xc4, 0x82, 0x4c, 0xfd, 0xe4, 0x9c, 0xd2, 0xe2, 0x92, 0xd4, 0x22, 0xfd,
	0x32, 0x43, 0xfd, 0x82, 0x24, 0xb0, 0x2d, 0x10, 0x6d, 0x46, 0x3b, 0x19, 0xb9, 0xb8, 0xfc, 0xf2,
	0x53, 0x52, 0x83, 0xc1, 0x56, 0x08, 0x85, 0x70, 0x71, 0x04, 0xa5, 0xa6, 0x67, 0x82, 0xd4, 0x0a,
	0x19, 0xe8, 0x21, 0x8c, 0xd4, 0x03, 0x19, 0xa9, 0x07, 0x33, 0x52, 0x2f, 0xb1, 0x20, 0x53, 0x0f,
	0x6a, 0xa4, 0x5e, 0x99, 0xa1, 0x5e, 0x41, 0x92, 0x1e, 0xc8, 0x0c, 0x29, 0x31, 0x3d, 0x88, 0x0b,
	0xf5, 0x60, 0x2e, 0xd4, 0x73, 0x05, 0xb9, 0x50, 0x28, 0x94, 0x8b, 0xd3, 0x23, 0x35, 0xb1, 0xa8,
	0x24, 0x29, 0x35, 0xb1, 0x84, 0x7a, 0xc6, 0x3a, 0x09, 0x9c, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91,
	0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x33, 0x1e, 0xcb, 0x31, 0x24, 0xb1, 0x81, 0x55, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xcd, 0xa9, 0x15, 0x53, 0x01, 0x00, 0x00,
}
