// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nodestatus/nodestatus.proto

/*
Package nodestatus is a generated protocol buffer package.

It is generated from these files:
	nodestatus/nodestatus.proto

It has these top-level messages:
	NodeInfo
	RegisteredReply
	Node
*/
package nodestatus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeInfo struct {
	Node    *Node             `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Address string            `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Tags    map[string]string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *NodeInfo) Reset()                    { *m = NodeInfo{} }
func (m *NodeInfo) String() string            { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()               {}
func (*NodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeInfo) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *NodeInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NodeInfo) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type RegisteredReply struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *RegisteredReply) Reset()                    { *m = RegisteredReply{} }
func (m *RegisteredReply) String() string            { return proto.CompactTextString(m) }
func (*RegisteredReply) ProtoMessage()               {}
func (*RegisteredReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisteredReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Node struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeInfo)(nil), "nodestatus.NodeInfo")
	proto.RegisterType((*RegisteredReply)(nil), "nodestatus.RegisteredReply")
	proto.RegisterType((*Node)(nil), "nodestatus.node")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NodeStatus service

type NodeStatusClient interface {
	Register(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*RegisteredReply, error)
}

type nodeStatusClient struct {
	cc *grpc.ClientConn
}

func NewNodeStatusClient(cc *grpc.ClientConn) NodeStatusClient {
	return &nodeStatusClient{cc}
}

func (c *nodeStatusClient) Register(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*RegisteredReply, error) {
	out := new(RegisteredReply)
	err := grpc.Invoke(ctx, "/nodestatus.NodeStatus/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NodeStatus service

type NodeStatusServer interface {
	Register(context.Context, *NodeInfo) (*RegisteredReply, error)
}

func RegisterNodeStatusServer(s *grpc.Server, srv NodeStatusServer) {
	s.RegisterService(&_NodeStatus_serviceDesc, srv)
}

func _NodeStatus_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStatusServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodestatus.NodeStatus/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStatusServer).Register(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nodestatus.NodeStatus",
	HandlerType: (*NodeStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _NodeStatus_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodestatus/nodestatus.proto",
}

func init() { proto.RegisterFile("nodestatus/nodestatus.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0x37, 0xed, 0xd4, 0xf5, 0x0d, 0x74, 0x3c, 0x86, 0x94, 0x0d, 0xa4, 0x04, 0xc1, 0x9e, 0x2a,
	0xc4, 0x83, 0xe2, 0xc5, 0x93, 0x07, 0x0f, 0x7a, 0x88, 0x7e, 0x81, 0x48, 0x9e, 0xa5, 0x38, 0x9a,
	0x91, 0x64, 0xc2, 0x3e, 0x99, 0x5f, 0x4f, 0x92, 0xb6, 0xae, 0xc8, 0x6e, 0xbf, 0x3f, 0xef, 0xbd,
	0xdf, 0x2f, 0x81, 0x55, 0x6b, 0x34, 0x39, 0xaf, 0xfc, 0xd6, 0xdd, 0xec, 0x61, 0xb5, 0xb1, 0xc6,
	0x1b, 0x84, 0xbd, 0xc2, 0x7f, 0x18, 0x4c, 0x5f, 0x8d, 0xa6, 0xe7, 0xf6, 0xd3, 0xe0, 0x15, 0x4c,
	0x82, 0x95, 0xb3, 0x82, 0x95, 0x33, 0x31, 0xaf, 0x46, 0x9b, 0x01, 0xca, 0xe8, 0x62, 0x0e, 0xa7,
	0x4a, 0x6b, 0x4b, 0xce, 0xe5, 0x49, 0xc1, 0xca, 0x4c, 0x0e, 0x14, 0x05, 0x4c, 0xbc, 0xaa, 0x5d,
	0x9e, 0x16, 0x69, 0x39, 0x13, 0x97, 0xe3, 0xfd, 0x21, 0xa3, 0x7a, 0x57, 0xb5, 0x7b, 0x6a, 0xbd,
	0xdd, 0xc9, 0x38, 0xbb, 0xbc, 0x83, 0xec, 0x4f, 0xc2, 0x39, 0xa4, 0x5f, 0xb4, 0x8b, 0xf9, 0x99,
	0x0c, 0x10, 0x17, 0x70, 0xfc, 0xad, 0xd6, 0x5b, 0xea, 0xa3, 0x3a, 0xf2, 0x90, 0xdc, 0x33, 0x7e,
	0x0d, 0xe7, 0x92, 0xea, 0xc6, 0x79, 0xb2, 0xa4, 0x25, 0x6d, 0xd6, 0x71, 0x98, 0xac, 0x35, 0xb6,
	0x3f, 0xd0, 0x11, 0x7e, 0xd1, 0xbd, 0x0a, 0xcf, 0x20, 0x69, 0x74, 0x6f, 0x25, 0x8d, 0x16, 0x2f,
	0x00, 0xa1, 0xd5, 0x5b, 0x2c, 0x88, 0x8f, 0x30, 0x1d, 0xce, 0xe1, 0xe2, 0x50, 0xf3, 0xe5, 0x6a,
	0xac, 0xfe, 0x8b, 0xe6, 0x47, 0x1f, 0x27, 0xf1, 0x73, 0x6f, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0xa5, 0x14, 0xa6, 0x7b, 0x01, 0x00, 0x00,
}
