// Code generated by mockery v1.0.0
package watch

import mock "github.com/stretchr/testify/mock"
import watch "github.com/slok/ragnarok/apimachinery/watch"

// MultiplexerFactory is an autogenerated mock type for the MultiplexerFactory type
type MultiplexerFactory struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *MultiplexerFactory) Get(id string) watch.Multiplexer {
	ret := _m.Called(id)

	var r0 watch.Multiplexer
	if rf, ok := ret.Get(0).(func(string) watch.Multiplexer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Multiplexer)
		}
	}

	return r0
}
