// Code generated by mockery v1.0.0
package watch

import mock "github.com/stretchr/testify/mock"
import watch "github.com/slok/ragnarok/apimachinery/watch"

// Multiplexer is an autogenerated mock type for the Multiplexer type
type Multiplexer struct {
	mock.Mock
}

// SendEvent provides a mock function with given fields: _a0
func (_m *Multiplexer) SendEvent(_a0 watch.Event) {
	_m.Called(_a0)
}

// StartWatcher provides a mock function with given fields:
func (_m *Multiplexer) StartWatcher() (watch.Watcher, error) {
	ret := _m.Called()

	var r0 watch.Watcher
	if rf, ok := ret.Get(0).(func() watch.Watcher); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Watcher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StopAll provides a mock function with given fields:
func (_m *Multiplexer) StopAll() {
	_m.Called()
}

// StopWatcher provides a mock function with given fields: _a0
func (_m *Multiplexer) StopWatcher(_a0 string) {
	_m.Called(_a0)
}
