// Code generated by mockery v1.0.0
package watch

import mock "github.com/stretchr/testify/mock"
import watch "github.com/slok/ragnarok/apimachinery/watch"

// Watcher is an autogenerated mock type for the Watcher type
type Watcher struct {
	mock.Mock
}

// GetChan provides a mock function with given fields:
func (_m *Watcher) GetChan() <-chan watch.Event {
	ret := _m.Called()

	var r0 <-chan watch.Event
	if rf, ok := ret.Get(0).(func() <-chan watch.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan watch.Event)
		}
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *Watcher) Stop() {
	_m.Called()
}
