// Code generated by mockery v1.0.0
package handler

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// ResourceHandler is an autogenerated mock type for the ResourceHandler type
type ResourceHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: w, r
func (_m *ResourceHandler) Create(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Delete provides a mock function with given fields: w, r, id
func (_m *ResourceHandler) Delete(w http.ResponseWriter, r *http.Request, id string) {
	_m.Called(w, r, id)
}

// Get provides a mock function with given fields: w, r, id
func (_m *ResourceHandler) Get(w http.ResponseWriter, r *http.Request, id string) {
	_m.Called(w, r, id)
}

// GetRoute provides a mock function with given fields:
func (_m *ResourceHandler) GetRoute() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// List provides a mock function with given fields: w, r, opts
func (_m *ResourceHandler) List(w http.ResponseWriter, r *http.Request, opts map[string]string) {
	_m.Called(w, r, opts)
}

// Update provides a mock function with given fields: w, r, id
func (_m *ResourceHandler) Update(w http.ResponseWriter, r *http.Request, id string) {
	_m.Called(w, r, id)
}

// Watch provides a mock function with given fields: w, r, opts
func (_m *ResourceHandler) Watch(w http.ResponseWriter, r *http.Request, opts map[string]string) {
	_m.Called(w, r, opts)
}
