// Code generated by mockery v1.0.0
package validator

import api "github.com/slok/ragnarok/api"
import mock "github.com/stretchr/testify/mock"
import validator "github.com/slok/ragnarok/apimachinery/validator"

// ObjectValidator is an autogenerated mock type for the ObjectValidator type
type ObjectValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: obj
func (_m *ObjectValidator) Validate(obj api.Object) validator.ErrorList {
	ret := _m.Called(obj)

	var r0 validator.ErrorList
	if rf, ok := ret.Get(0).(func(api.Object) validator.ErrorList); ok {
		r0 = rf(obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(validator.ErrorList)
		}
	}

	return r0
}
