// Code generated by mockery v1.0.0
package informer

import api "github.com/slok/ragnarok/api"

import mock "github.com/stretchr/testify/mock"
import watch "github.com/slok/ragnarok/apimachinery/watch"

// ListerWatcher is an autogenerated mock type for the ListerWatcher type
type ListerWatcher struct {
	mock.Mock
}

// List provides a mock function with given fields: opts
func (_m *ListerWatcher) List(opts api.ListOptions) (api.ObjectList, error) {
	ret := _m.Called(opts)

	var r0 api.ObjectList
	if rf, ok := ret.Get(0).(func(api.ListOptions) api.ObjectList); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.ObjectList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(api.ListOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Watch provides a mock function with given fields: opts
func (_m *ListerWatcher) Watch(opts api.ListOptions) (watch.Watcher, error) {
	ret := _m.Called(opts)

	var r0 watch.Watcher
	if rf, ok := ret.Get(0).(func(api.ListOptions) watch.Watcher); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Watcher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(api.ListOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
