// Code generated by mockery v1.0.0
package informer

import api "github.com/slok/ragnarok/api"

import mock "github.com/stretchr/testify/mock"

// ObjectIndexKeyer is an autogenerated mock type for the ObjectIndexKeyer type
type ObjectIndexKeyer struct {
	mock.Mock
}

// GetKey provides a mock function with given fields: obj
func (_m *ObjectIndexKeyer) GetKey(obj api.Object) (string, error) {
	ret := _m.Called(obj)

	var r0 string
	if rf, ok := ret.Get(0).(func(api.Object) string); ok {
		r0 = rf(obj)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(api.Object) error); ok {
		r1 = rf(obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
