// Code generated by mockery v1.0.0
package service

import mock "github.com/stretchr/testify/mock"

import v1 "github.com/slok/ragnarok/api/chaos/v1"

// Scheduler is an autogenerated mock type for the Scheduler type
type Scheduler struct {
	mock.Mock
}

// Schedule provides a mock function with given fields: experiment
func (_m *Scheduler) Schedule(experiment *v1.Experiment) ([]*v1.Failure, error) {
	ret := _m.Called(experiment)

	var r0 []*v1.Failure
	if rf, ok := ret.Get(0).(func(*v1.Experiment) []*v1.Failure); ok {
		r0 = rf(experiment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.Failure)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.Experiment) error); ok {
		r1 = rf(experiment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
