// Code generated by mockery v1.0.0
package v1

import clusterv1 "github.com/slok/ragnarok/client/cluster/v1"
import mock "github.com/stretchr/testify/mock"
import v1 "github.com/slok/ragnarok/api/cluster/v1"

// Node is an autogenerated mock type for the Node type
type Node struct {
	mock.Mock
}

// Create provides a mock function with given fields: node
func (_m *Node) Create(node *v1.Node) (*v1.Node, error) {
	ret := _m.Called(node)

	var r0 *v1.Node
	if rf, ok := ret.Get(0).(func(*v1.Node) *v1.Node); ok {
		r0 = rf(node)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.Node) error); ok {
		r1 = rf(node)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Node) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *Node) Get(id string) (*v1.Node, error) {
	ret := _m.Called(id)

	var r0 *v1.Node
	if rf, ok := ret.Get(0).(func(string) *v1.Node); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: opts
func (_m *Node) List(opts clusterv1.NodeListOptions) ([]*v1.Node, error) {
	ret := _m.Called(opts)

	var r0 []*v1.Node
	if rf, ok := ret.Get(0).(func(clusterv1.NodeListOptions) []*v1.Node); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(clusterv1.NodeListOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: node
func (_m *Node) Update(node *v1.Node) (*v1.Node, error) {
	ret := _m.Called(node)

	var r0 *v1.Node
	if rf, ok := ret.Get(0).(func(*v1.Node) *v1.Node); ok {
		r0 = rf(node)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.Node) error); ok {
		r1 = rf(node)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Watch provides a mock function with given fields: opts
func (_m *Node) Watch(opts clusterv1.NodeListOptions) (clusterv1.NodeWatch, error) {
	ret := _m.Called(opts)

	var r0 clusterv1.NodeWatch
	if rf, ok := ret.Get(0).(func(clusterv1.NodeListOptions) clusterv1.NodeWatch); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clusterv1.NodeWatch)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(clusterv1.NodeListOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
