// Code generated by mockery v1.0.0
package client

import mock "github.com/stretchr/testify/mock"

// FailureExpectedStateHandler is an autogenerated mock type for the FailureExpectedStateHandler type
type FailureExpectedStateHandler struct {
	mock.Mock
}

// ProcessFailureExpectedStates provides a mock function with given fields: enabledStateIDs, disabledStateIDs
func (_m *FailureExpectedStateHandler) ProcessFailureExpectedStates(enabledStateIDs []string, disabledStateIDs []string) error {
	ret := _m.Called(enabledStateIDs, disabledStateIDs)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, []string) error); ok {
		r0 = rf(enabledStateIDs, disabledStateIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
