// Code generated by mockery v1.0.0
package client

import mock "github.com/stretchr/testify/mock"
import v1 "github.com/slok/ragnarok/api/chaos/v1"

// FailureStateHandler is an autogenerated mock type for the FailureStateHandler type
type FailureStateHandler struct {
	mock.Mock
}

// ProcessFailureStates provides a mock function with given fields: failures
func (_m *FailureStateHandler) ProcessFailureStates(failures []*v1.Failure) error {
	ret := _m.Called(failures)

	var r0 error
	if rf, ok := ret.Get(0).(func([]*v1.Failure) error); ok {
		r0 = rf(failures)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
