// Code generated by mockery v1.0.0
package client

import mock "github.com/stretchr/testify/mock"
import v1 "github.com/slok/ragnarok/api/cluster/v1"

// Status is an autogenerated mock type for the Status type
type Status struct {
	mock.Mock
}

// NodeHeartbeat provides a mock function with given fields: node
func (_m *Status) NodeHeartbeat(node *v1.Node) error {
	ret := _m.Called(node)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Node) error); ok {
		r0 = rf(node)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterNode provides a mock function with given fields: node
func (_m *Status) RegisterNode(node *v1.Node) error {
	ret := _m.Called(node)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Node) error); ok {
		r0 = rf(node)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
