// Code generated by mockery v1.0.0
package attack

import context "context"
import mock "github.com/stretchr/testify/mock"

// Attacker is an autogenerated mock type for the Attacker type
type Attacker struct {
	mock.Mock
}

// Apply provides a mock function with given fields: ctx
func (_m *Attacker) Apply(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Revert provides a mock function with given fields:
func (_m *Attacker) Revert() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
